name: Blocking Objection
description: Precise blocking objection or counterexample
title: "Objection: URF-P-XXXX@vX.Y.Z"
labels: ["objection","blocking"]
body:
  - type: input
    id: manuscript_id
    attributes:
      label: Manuscript ID
    validations:
      required: true

  - type: input
    id: claim
    attributes:
      label: Claim reference
      description: Theorem or lemma identifier
    validations:
      required: true

  - type: textarea
    id: objection
    attributes:
      label: Objection
      description: Exact missing assumption, lemma, or counterexample
    validations:
      required: true
