name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Lean toolchain from repo
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          source $HOME/.elan/env
          elan toolchain install $(cat lean-toolchain)
          elan default $(cat lean-toolchain)

      - name: Build
        run: |
          source $HOME/.elan/env
          lake update
          lake build

