name: Lean CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Lean
        uses: leanprover/lean-action@v1
        with:
          toolchain: leanprover/lean4:v4.27.0

      - name: Lake update
        run: lake update

      - name: Check Lean toolchain
        run: ./scripts/check-lean-toolchain.sh

      - name: Build
        run: lake build

